version: 2
jobs:
  run_tests:
    # This is the base environment that Circle will use
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      - run: sudo apt-get update
      - checkout

      # restore pip cache to speed up installations
      - restore_cache:
          keys:
            - pip-tests-cache-0-{{ checksum "./requirements.txt" }}

      # Using conda manager for python environment and packages
      - run:
          name: Install miniconda
          command: |
            wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O ~/miniconda.sh;
            chmod +x ~/miniconda.sh;
            ~/miniconda.sh -b -p ~/miniconda;
            echo "export PATH=~/miniconda/bin:$PATH" >> $BASH_ENV;

      # Setup the python environment
      - run:
          name: Setup Python environment
          command: |
            conda update --yes --quiet conda
            conda create -n testenv --yes python=3.6
            source activate testenv
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            python setup.py develop

      # XXX: install MNE `master` temporarily until MNE-Python 0.20.1 is
      # released ... see: https://github.com/bids-standard/pybv/pull/39
      - run:
          name: install MNE-Python master
          command: |
            source activate testenv
            pip install -U https://api.github.com/repos/mne-tools/mne-python/zipball/master

      # Save cache
      - save_cache:
          key: pip-tests-cache-0-{{ checksum "./requirements.txt" }}
          paths:
            - ~/.cache/pip

      # Run tests and upload coverage
      - run:
          name: Running tests and coverage + uploading it
          command: |
            source activate testenv
            pytest --cov=./pybv --cov-report=xml
            flake8 .
            bash <(curl -s https://codecov.io/bash)

  build_docs:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      - run: sudo apt-get update
      - checkout

      # restore pip cache to speed up installations
      - restore_cache:
          keys:
            - pip-docs-cache-0-{{ checksum "./requirements.txt" }}

      # Using conda manager for python environment and packages
      - run:
          name: Install miniconda
          command: |
            wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O ~/miniconda.sh;
            chmod +x ~/miniconda.sh;
            ~/miniconda.sh -b -p ~/miniconda;
            echo "export PATH=~/miniconda/bin:$PATH" >> $BASH_ENV;

      # Setup the python environment
      - run:
          name: Setup Python environment
          command: |
            conda update --yes --quiet conda
            conda create -n testenv --yes python=3.6
            source activate testenv
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            python setup.py develop

      # Save cache
      - save_cache:
          key: pip-docs-cache-0-{{ checksum "./requirements.txt" }}
          paths:
            - ~/.cache/pip

      # Build the docs
      - run:
          name: Build docs to store
          command: |
            source activate testenv
            cd docs
            make clean
            make html

      # Tell Circle to store the documentation output in a folder that we can access later
      - store_artifacts:
          path: docs/_build/html/
          destination: html

# Tell CircleCI to use this workflow when it builds the site
workflows:
  version: 2
  default:
    jobs:
      - run_tests
      - build_docs:
          requires:
            - run_tests
